name: Say hello to everyone
on: push

jobs:
  build:
    name: Say hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./hello-actions
        with:
          MY_NAME: "Jeff"
